services:
  db:
    image: postgres:16-alpine
    container_name: transcendence_db
    restart: unless-stopped
    env_file:
      - .env
    envirronnement:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    port:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      start_period: 10s
    network:
      -transcendence_net

  redis:                                          # ← nouveau service, même indentation que "db:"
    image: redis:7-alpine
    container_name: transcendence_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep -q PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - transcendence_net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendence_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - transcendence_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:5173"
    networks:
      - transcendence_net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
networks:
  transcendence_net:
    driver: bridge
