apiVersion: 1
groups:
    - orgId: 1
      name: infra-critical
      folder: infra-alerts
      interval: 1m
      rules:
        - uid: bfwtyhccxd5vkc
          title: PostgreSQL Down
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                disableTextWrap: false
                editorMode: builder
                expr: up{job="postgres-exporter"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: PostgreSQL has been inactive for more than 1 minute
          labels: {}
          isPaused: false
          notification_settings:
            receiver: webhook-demo
